"""empty message

Revision ID: 44a05cb8d9e6
Revises: f9122b1bbffb
Create Date: 2025-02-10 14:31:26.822417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a05cb8d9e6'
down_revision = 'f9122b1bbffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index('ix_workers_full_name')

    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('worker_post', sa.VARCHAR(length=64), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index('ix_workers_full_name', ['full_name'], unique=1)

    # ### end Alembic commands ###
