"""empty message

Revision ID: 5cb9865c3c66
Revises: 69e6b9264afb
Create Date: 2025-02-08 19:47:11.432674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb9865c3c66'
down_revision = '69e6b9264afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('worker_post', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('contacts', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_full_name'), ['full_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_full_name'))

    op.drop_table('workers')
    # ### end Alembic commands ###
