"""add feedback model

Revision ID: ca3a08961515
Revises: 
Create Date: 2025-02-08 15:19:35.198711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3a08961515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consult_name', sa.String(length=128), nullable=False),
    sa.Column('date_feed', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_consult_name'), ['consult_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_date_feed'), ['date_feed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_date_feed'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_consult_name'))

    op.drop_table('feedbacks')
    # ### end Alembic commands ###
