"""empty message

Revision ID: f9122b1bbffb
Revises: 5b05d5fc8f35
Create Date: 2025-02-10 14:18:40.115138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9122b1bbffb'
down_revision = '5b05d5fc8f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index('ix_workers_full_name')
        batch_op.create_index(batch_op.f('ix_workers_full_name'), ['full_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_full_name'))
        batch_op.create_index('ix_workers_full_name', ['full_name'], unique=False)

    # ### end Alembic commands ###
